# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GEOMETRY: voyager
  LAYOUT_ID: r9RqJ

tasks:
  default:
    cmds:
    - task: sync
    - task: build

  sync:
    cmds:
      # TODO require running on main branch
      - git fetch origin main
      - task: pull-oryx
      - git merge --no-edit -Xignore-all-space oryx
  
  pull-oryx:
    desc: pull latest version of voyager source file
    vars:
      ORYX_WORKTREE_DIR:
        # TODO stop and ask for worktree creation if missing
        sh: |
           git worktree list --porcelain | \
             grep -a2 heads/oryx | grep -E "^worktree " | awk '{ print $2}'
      GQL_QUERY: '{"query":"query getLayout($hashId: String!, $revisionId: String!, $geometry: String) {layout(hashId: $hashId, geometry: $geometry, revisionId: $revisionId) {  revision { hashId, qmkVersion, title }}}","variables":{"hashId":"{{.LAYOUT_ID}}","geometry":"{{.GEOMETRY}}","revisionId":"latest"}}'
      METADATA:
        sh: |
          curl --location 'https://oryx.zsa.io/graphql'  \
            --header 'Content-Type: application/json'  \
            --data '{{.GQL_QUERY}}' \
            | jq -c '.data.layout.revision'
      HASH_ID:
        ref: '(.METADATA | fromJson).hashId' 
      CHANGE_DESC:
        ref: '(.METADATA | fromJson).title' 
    dir: '{{.ORYX_WORKTREE_DIR}}'
    cmds:
      - |
          echo "pwd: $(pwd)"
      - cmd: curl -L "https://oryx.zsa.io/source/{{.HASH_ID}}" -o source.zip
      - unzip -oj source.zip '*_source/*' -d 'keyboards/zsa/voyager/keymaps/yorkxin'
      - defer: rm source.zip
      - echo '{{.METADATA}}' > metadata.json
      - git add keyboards metadata.json
      - cmd: |
          printf "✨(oryx): %s\n" "{{.CHANGE_DESC}}" | git commit -F - || echo "No layout change"

  docker_image:
    cmds:
      - docker pull ghcr.io/qmk/qmk_cli

  build:
    deps:
      - docker_image
    vars:
      normalized_layout_geometry: 
        sh: echo "{{.GEOMETRY}}" | sed 's/\//_/g'
      QMK_VERSION:
        sh: cat metadata.json | jq -r ".qmkVersion" | xargs printf "%.0f"
    cmds:
      - docker volume create qmk_firmware_cache
      # Build the layout
      - docker run --rm
          --mount source=qmk_firmware_cache,target=/qmk_firmware
          -v .:/qmk_userspace
          ghcr.io/qmk/qmk_cli /bin/sh -c "
          qmk setup zsa/qmk_firmware -b firmware{{.QMK_VERSION}} -y  &&
          qmk userspace-compile"

      # Find and export built layout
      - find . -maxdepth 1 -type f -name "*{{.normalized_layout_geometry}}*.bin"
