## inspired from https://github.com/poulainpi/oryx-with-custom-qmk

name: Sync oryx source code to main

on:
  workflow_dispatch:
    inputs:
      layout_id:
        description: "Layout id available in URL https://configure.zsa.io/voyager/layouts/[ID_IS_HERE]/latest"
        required: true
        default: "r9RqJ"
      layout_geometry:
        description: "Keyboard type"
        type: choice
        options:
          - voyager
          - moonlander/reva
          - moonlander/revb
          - ergodox_ez
          - ergodox_ez/m32u4/glow
          - ergodox_ez/m32u4/shine
          - ergodox_ez/stm32
          - ergodox_ez/stm32/glow
          - ergodox_ez/stm32/shine
          - planck_ez
          - planck_ez/glow
        default: voyager

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0             # otherwise, you will fail to push refs to dest repo

      - name: Git setup
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Task
        uses: go-task/setup-task@v2

      - name: task sync
        run: task sync

      - name: Git push
        run: |
          git push --all
